---

# -- Node management options for each selenium grid node managed by this chart.
nodes:

  # This section will provide you with an overview of theoretically, how many tests
  # you can run concurrently with the base setup. It is simply replicas X concurrency, 
  # and that gives you the estimated number of concurrent tests/sessions you can run 
  # with this cluster.

  # -- Specify the number of selenium node pods you want spun up as a base case.
  replicas: 1

  # -- Specify the maximum concurrency level that you want for each node pod.
  concurrency: 1

  # -- Specify the minimum number of replicas for the selenium node pod within the cluster.
  minReplicas: 1

  # -- Specify the maximum number of replicas for the selenium node pod within the cluster.
  maxReplicas: 3

  # -- Specify the image for the node instances.
  image: docker.io/selenium/node-chrome:latest

  resources:
    limits:
      # -- Specify the maximum memory for every selenium node within the cluster.
      memory: "1Gi"

      # -- Specify the maximum cpu for every selenium node within the cluster.
      cpu: "1"

# -- Hub management options for the hub node managed by this chart. 
hub:

  # -- Specify the image for the hub instance.
  image: docker.io/selenium/hub:4.8.0

  resources:
    limits:
      # -- Specify the maximum memory for the hub instance within the cluster.
      memory: "1Gi"
  
      # -- Specify the maximum cpu for the hub instance within the cluster.
      cpu: "1"
