{{ if eq .Values.cloud_provider "AWS" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "aws-ingress"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "hubsvc"
                port:
                  number: 9994
{{ end }}