---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodepoolautoscaler
  namespace: {{ .Release.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selnodepool
  minReplicas: {{ .Values.nodes.minReplicas }}
  maxReplicas: {{ .Values.nodes.maxReplicas }}
  metrics:
  - type: External
    external:
      metric:
        name: "selenium_grid_session_util_percent"
      target:
        type: "Value"
        value: {{ .Values.nodes.scalingUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.nodes.stabilizationWindowSeconds }}
