---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  namespace: {{ .Release.namespace }}
spec:
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      containers:
      - name: hub
        image: {{ .Values.hub.image }}
        resources:
          limits:
            memory: {{ .Values.hub.resources.limits.memory | quote }}
            cpu: {{ .Values.hub.resources.limits.cpu | quote }}
        ports:
        - containerPort: 4444
        - containerPort: 4443
        - containerPort: 4442
        env:
          # In milliseconds, maps to "--session-retry-interval"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "250"
          # In seconds, how long a test can be idle before being killed
          - name: SE_NODE_SESSION_TIMEOUT
            value: {{ .Values.hub.session_timeout_sec | quote }}
          # In seconds, how long a test can sit in the queue before being dropped
          - name: SE_SESSION_REQUEST_TIMEOUT
            value: {{ .Values.hub.session_queue_timeout_sec | quote }}
          # In seconds, how frequently the hub should send a health probe to the selenium nodes
          - name: SE_OPTS
            value: "--healthcheck-interval 5"
