---
apiVersion: v1
kind: Service
metadata:
  name: hubsvc
  namespace: {{ .Release.namespace }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {
      "9994": "hubsvc-ui-backendconfig"
      }}'
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    {{- if ne .Values.cloud_specific_config.Azure.load_balancer_ip "none" }}
    service.beta.kubernetes.io/azure-load-balancer-ipv4: {{ .Values.cloud_specific_config.Azure.load_balancer_ip | quote }}
    {{- end }}
spec:
{{- if or (eq .Values.cloud_provider "AWS") (eq .Values.cloud_provider "Azure") }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
  selector:
    app: hub
  ports:
  - port: 9992
    targetPort: 4442
    name: pubport
  - port: 9993
    targetPort: 4443
    name: subport
  - port: 9994
    targetPort: 4444
    name: uiport
{{- if or (eq .Values.cloud_provider "local") (eq .Values.cloud_provider "GCP") }}
    nodePort: 30000
{{- end }}
---
{{ if eq .Values.cloud_provider "GCP" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hubsvc-ui-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 25
    port: 30000
    type: HTTP
    requestPath: /ui
  timeoutSec: 600
{{ end }}