---
apiVersion: v1
kind: Service
metadata:
  name: hubsvc
  namespace: {{ .Release.namespace }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {
      "9994": "hubsvc-ui-backendconfig"
      }}'
spec:
{{- if eq .Values.cloud_provider "AWS" }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
  selector:
    app: hub
  ports:
  - port: 9992
    targetPort: 4442
    name: pubport
  - port: 9993
    targetPort: 4443
    name: subport
  - port: 9994
    targetPort: 4444
    name: uiport
    nodePort: 30000
{{- if eq .Values.cloud_provider "AWS" }}
  - port: 80
    targetPort: 4444
    name: awsuiport
{{- end }}
---
{{ if eq .Values.cloud_provider "GCP" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hubsvc-ui-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 25
    port: 30000
    type: HTTP
    requestPath: /ui
  timeoutSec: 600
{{ end }}