alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: custom_exporter
        static_configs:
          - targets:
            - exportersvc.default:8321 # TODO: factor out this port somewhere
        scrape_interval: 1s