apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
spec:
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      containers:
      - name: hub
        image: docker.io/selenium/hub:4.8.0
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 4444
        - containerPort: 4443
        - containerPort: 4442
        env:
          # In milliseconds, maps to "--session-retry-interval"
          - name: SE_SESSION_RETRY_INTERVAL
            value: "250"
          - name: SE_OPTS
            value: "--healthcheck-interval 5"
