apiVersion: v1
kind: Service
metadata:
  name: hubsvc
spec:
  type: NodePort
  selector:
    app: hub
  ports:
  - port: 9992
    targetPort: 4442
    name: pubport
  - port: 9993
    targetPort: 4443
    name: subport
  - port: 9994
    targetPort: 4444
    name: uiport
    nodePort: 30000