apiVersion: apps/v1
kind: Deployment
metadata:
  name: selnodepool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selnodepool
  template:
    metadata:
      labels:
        app: selnodepool
    spec:
      containers:
      - name: selnodepool
        image: selenium/node-chrome
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5555
        env:
          - name: SE_EVENT_BUS_HOST
            value: "hubsvc.default"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "9992"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "9993"
          - name: SE_NODE_MAX_SESSIONS
            value: "3"
          - name: SE_NODE_OVERRIDE_MAX_SESSIONS
            value: "true"
