
name: Build and push hub router image

on:
  # release:
  push:
    tags:
      - "*"

jobs:
  hub-router-build-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: Buildah Build
      uses: redhat-actions/buildah-build@v2.11
      with:
        context: hub_router_warp
        containerfiles: hub_router_warp/Dockerfile
        image: ghcr.io/fire833/capstone/hub_router_warp
        tags: latest v${{ github.ref_name }}
        layers: true

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        registry: ghcr.io
        image: ghcr.io/fire833/capstone/hub_router_warp
        tags: latest v${{ github.ref_name }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCRPAT }}
        tls-verify: true
