---
name: Run tests

on:
  pull_request:
    branches:
      - "*"

  # release:
  
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  exporter-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run tests
      run: cd exporter/ && go test -v -cover ./...

  helm-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Chart
      run: helm template test selenium-grid-cluster/ --debug

    - name: Lint chart
      run: helm lint selenium-grid-cluster/ --debug
